### ISSUE TITLE
fmovie 无法使用磁力链下载，搜索不到资源

### ISSUE THREAD

**Issue by MassenEvan** [luiyezheng/Alfred-workflow-china#1]
貌似是磁力链网站挂了？输入 fmovie + 电影名称 得不到任何返回结果。

**Comment by Textcat** [comment]
是啊，就是挂了，磁力网站经常会挂，比较郁闷，我已经用过两个磁力网站了，都挂了,主要磁力网站经常更换域名或是被和谐掉 @MassenEvan

**Comment by Textcat** [comment]
问题不大，已经修复，现在应该可以使用了 @MassenEvan

**Comment by MassenEvan** [comment]
非常感谢！ @luiyezheng
