### ISSUE TITLE
是否已经不更新了？

### ISSUE THREAD

**Issue by luisxin** [luiyezheng/Alfred-workflow-china#3]
用豆瓣查询电影 结果不对，比如美人鱼，就没有2016年的？

**Comment by Textcat** [comment]
我在我的电脑上试了一下，豆瓣搜索电影好像没有什么问题呀~不过磁力搜索有点问题，已经修复，如果还找不到资源的话那就是磁力网站本身的问题了

**Comment by luisxin** [comment]
好的，感谢。
